// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8L0F_j_aPNUzDZmTBBGONT_HOrTevng',
    appId: '1:348942507169:web:70f7fa0bb22c6705b764e0',
    messagingSenderId: '348942507169',
    projectId: 'meishimanager',
    authDomain: 'meishimanager.firebaseapp.com',
    storageBucket: 'meishimanager.firebasestorage.app',
    measurementId: 'G-G927NHHK6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHr2LlOYueakRfgIYiKguhz0oMbUyUKg',
    appId: '1:348942507169:android:c42983a2205f84d1b764e0',
    messagingSenderId: '348942507169',
    projectId: 'meishimanager',
    storageBucket: 'meishimanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKx-AckiZU7a3cfsYfG07wRQPPlF16-s',
    appId: '1:348942507169:ios:323d6bdd791e05bdb764e0',
    messagingSenderId: '348942507169',
    projectId: 'meishimanager',
    storageBucket: 'meishimanager.firebasestorage.app',
    iosBundleId: 'com.obfall.meishiManager',
  );
}
